# -*- coding: utf-8 -*-
"""Eksperimen_Muhammad Fathi Farhat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eounn30iPJ5sxI-bQ4pVrvDN0zccoPM-

# **1. Perkenalan Dataset**

Tahap pertama, Anda harus mencari dan menggunakan dataset dengan ketentuan sebagai berikut:

1. **Sumber Dataset**:  
   Dataset dapat diperoleh dari berbagai sumber, seperti public repositories (*Kaggle*, *UCI ML Repository*, *Open Data*) atau data primer yang Anda kumpulkan sendiri.

---

Dataset yang digunakan adalah dataset churn prediction yang diperoleh dari platform Kaggle dengan link berikut: https://www.kaggle.com/datasets/muhammadshahidazeem/customer-churn-dataset

# **2. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

import os
import zipfile
import pandas as pd
import numpy as np
import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

"""# **3. Memuat Dataset**

Pada tahap ini, Anda perlu memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan Anda menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan

---

Akan dilakukan load dataset langsung dari Kaggle
"""

# Load dataset dari GitHub
# pada tahap ini, dataset yang sudah didownload dari kaggle diupload di repository github 

url = "https://raw.githubusercontent.com/farhatfathi/Eksperimen_SML_Muhammad-Fathi-Farhat/refs/heads/main/Dataset_raw.csv"
df = pd.read_csv(url, delimiter=',')

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, Anda akan melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

# melihat sekilas data
print(df.shape)
df.head()

# melihat info data
df.info()

# melihat deskripsi statistik data
df.describe()

# mengetahui dimensi data
df.shape

"""Data memiliki 12 kolom dengan 64374 baris"""

# cek null values
df.isnull().sum()

"""Dataset tidak memiliki null values"""

# cek duplicate data
df.duplicated().sum()

"""Dataset tidak memiliki data duplikat"""

# Pisahkan kolom berdasarkan tipe datanya
numerical_col = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_col = df.select_dtypes(include=['object', 'category']).columns.tolist()

print("Numerical columns:", numerical_col)
print("Categorical columns:", categorical_col)

# cek outliers
outliers_iqr = {}

for col in numerical_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cari baris yang outlier
    outlier_mask = (df[col] < lower_bound) | (df[col] > upper_bound)
    outliers_iqr[col] = outlier_mask.sum()

# Tampilkan jumlah outlier per kolom
print("Jumlah outliers (IQR method) per kolom:")
print(outliers_iqr)

"""Dataset tidak memiliki outliers"""

# cek distribusi Churn data
plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Churn', palette='Set2')

plt.title('Distribusi Target: Churn')
plt.xlabel('Churn (0 = Tidak Churn, 1 = Churn)')
plt.ylabel('Jumlah Customer')
plt.xticks([0, 1], ['Tidak Churn', 'Churn'])
plt.show()

"""Distribusi data churn cukup berimbang

# **5. Data Preprocessing**

Pada tahap ini, data preprocessing adalah langkah penting untuk memastikan kualitas data sebelum digunakan dalam model machine learning.

Jika Anda menggunakan data teks, data mentah sering kali mengandung nilai kosong, duplikasi, atau rentang nilai yang tidak konsisten, yang dapat memengaruhi kinerja model. Oleh karena itu, proses ini bertujuan untuk membersihkan dan mempersiapkan data agar analisis berjalan optimal.

Berikut adalah tahapan-tahapan yang bisa dilakukan, tetapi **tidak terbatas** pada:
1. Menghapus atau Menangani Data Kosong (Missing Values)
2. Menghapus Data Duplikat
3. Normalisasi atau Standarisasi Fitur
4. Deteksi dan Penanganan Outlier
5. Encoding Data Kategorikal
6. Binning (Pengelompokan Data)

Cukup sesuaikan dengan karakteristik data yang kamu gunakan yah. Khususnya ketika kami menggunakan data tidak terstruktur.
"""

# encoding data kategorikal dengan ordinal encoder
categorical_cols = df.select_dtypes(include=['object']).columns

# Inisialisasi encoder
encoder = OrdinalEncoder()

# Transformasi dan simpan hasilnya ke DataFrame baru
df[categorical_cols] = encoder.fit_transform(df[categorical_cols])

df.head()

# df_preprocessed adalah salinan df tanpa CustomerID
df_preprocessed = df.copy().drop('CustomerID', axis=1)
columns_to_scale = [col for col in df_preprocessed.columns if col != 'Churn']

# scaling df except Churn
scaler = StandardScaler()
df_preprocessed[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

df_preprocessed

# menyimpan preprocessed dataset
df_preprocessed = pd.DataFrame(df_preprocessed, columns=df.columns)
df_preprocessed.to_csv('df_preprocessed.csv', index=False)
