name: Run Preprocessing

on:
  workflow_dispatch:  # Bisa dijalankan manual dari GitHub UI
  push:
    paths:
      - 'Dataset_raw.csv'
      - 'preprocessing/automate_Muhammad-Fathi-Farhat.py'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Muhammad-Fathi-Farhat.py
